name: search_algorithms
description: A Dart package providing various search algorithms like Binary Search, Linear Search, and Jump Search.
version: 1.0.0
author: abdirahmonovakramjon@gmail.com
homepage: https://github.com/yourusername/search_algorithms
repository: https://github.com/yourusername/search_algorithms

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.yourcompany.search_algorithms
        pluginClass: SearchAlgorithmsPlugin
      ios:
        pluginClass: SearchAlgorithmsPlugin

