name: search_algorithms_with_akrom
description: A Dart package providing various search algorithms like Binary Search, Linear Search, and Jump Search.
version: 1.0.0
homepage: https://github.com/Abdirakhmonov/search_algorithms
repository: https://github.com/Abdirakhmonov/search_algorithms
environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

license: MIT
